AllCops:
  TargetRubyVersion: 3.3.5

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 100

Metrics/MethodLength:
  Max: 12
